### ISSUE TITLE
[css-backgrounds-3] Steps to Recommendation

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#10010]
(Also css-backgrounds-3 is basically a REC that's just missing an implementation report so definitely anything other than an error correction goes in css-backgrounds-4.)

_Originally posted by @fantasai in https://github.com/w3c/csswg-drafts/issues/6739#issuecomment-950031510_

**Comment by svgeesus** [comment]
The [implementation report](https://test.csswg.org/harness/results/css-backgrounds-3_dev/grouped/) linked from the current spec points to the old, unmaintained, manually-run Shepherd testsuite, not to WPT. **128** tests are listed.

There are no WPT annotations. There are **763** tests (**5556** subtests) in WPT, although these cover all levels.

I feel that the modern, maintained, automatically-run WPT tests are better in general to determine whether to advance to Proposed Rec. I understand that adding WPT annotations to a Bikeshed spec is a bunch of work, but it would be an improvement.

**Comment by svgeesus** [comment]
I will try to add the WPT annotations

**Comment by svgeesus** [comment]
> I will try to add the WPT annotations

[Done](https://github.com/w3c/csswg-drafts/commit/e3a41932ea33d1587882b33c6925a69eb78f55a1)

**Comment by svgeesus** [comment]
Not quite fully implemented but getting there

![image](https://github.com/user-attachments/assets/958fc583-a58d-4c7b-9d5d-9fea951e819f)

Chrome 127: **5809/6195**
Firefox 129: **5846/6206**
Safari 17: **5778/6206**
Edge 127: **5818/6206**

**Comment by svgeesus** [comment]
[Border image was part of Interop 2023](https://wpt.fyi/results/css/css-backgrounds?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssborderimage)

**Comment by svgeesus** [comment]
[Background size](https://wpt.fyi/results/css/css-backgrounds/background-size?label=experimental&label=master&aligned) is looking a bit rough, especially with [vector images](https://wpt.fyi/results/css/css-backgrounds/background-size/vector?label=experimental&label=master&aligned).

**Comment by SebastianZ** [comment]
Regarding background size, we still need to incorporate the changes resolved on in #7802. That requires an HTTP Archive request first, though.

Sebastian

**Comment by SebastianZ** [comment]
Besides that, there are still a few [remaining issues](https://github.com/w3c/csswg-drafts/issues/?q=is%3Aissue+state%3Aopen+background-size+label%3Acss-backgrounds-3) that should be solved or moved to Backgrounds 4 or Borders 4, first.

Sebastian

**Comment by AtkinsSJ** [comment]
> [Border image was part of Interop 2023](https://wpt.fyi/results/css/css-backgrounds?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssborderimage)

I'd like to bring up #12854: the interop on `border-image` isn't as good as the WPT page makes it look.

**Comment by SebastianZ** [comment]
> > [Border image was part of Interop 2023](https://wpt.fyi/results/css/css-backgrounds?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-cssborderimage)
> 
> I'd like to bring up [#12854](https://github.com/w3c/csswg-drafts/issues/12854): the interop on `border-image` isn't as good as the WPT page makes it look.

FWIW, https://wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&aligned&q=border-image shows the full test coverage for `border-image-*`. If there are tests missing, they should be added.

Regarding the [remaining issues](https://github.com/w3c/csswg-drafts/issues?q=is%3Aissue%20state%3Aopen%20label%3Acss-backgrounds-3), I currently see 4-5 essential ones:

- [ ] https://github.com/w3c/csswg-drafts/issues/2324 (just needs edits)
- [x] https://github.com/w3c/csswg-drafts/issues/7103
- [ ] https://github.com/w3c/csswg-drafts/issues/7164 (just needs edits)
- [x] https://github.com/w3c/csswg-drafts/issues/7802
  See https://github.com/w3c/csswg-drafts/pull/13053 and https://github.com/w3c/fxtf-drafts/pull/617.
- [ ] https://github.com/w3c/csswg-drafts/issues/9916 (just needs edits)
- [x] https://github.com/w3c/csswg-drafts/issues/11169
- [ ] https://github.com/w3c/csswg-drafts/issues/12849 (may just be editorial)
- [X] https://github.com/w3c/csswg-drafts/issues/11494

Sebastian

**Comment by SebastianZ** [comment]
I just realized that the [resolution of #2324](https://github.com/w3c/csswg-drafts/issues/2324#issuecomment-380036663) also targets CSS Backgrounds 3. So I've added it to the checklist.

Sebastian

**Comment by SebastianZ** [comment]
And there's also a [resolution in #7164](https://github.com/w3c/csswg-drafts/issues/7164#issuecomment-1201340918), which seems should be added level 3. So added it, as well.

Sebastian

**Comment by AtkinsSJ** [comment]
> FWIW, [wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&aligned&q=border-image](https://wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&aligned&q=border-image) shows the full test coverage for `border-image-*`. If there are tests missing, they should be added.

The issue isn't missing tests, it's that the serialization tests allow several options for the output. That means different browsers can have different serializations and still all pass the tests, even though they don't do the same thing. For authors to be able to use that output, it needs to be consistent. (Also for my own selfish reasons, I'd like to know which one we should be doing in Ladybird. 😅 )

**Comment by kbabbitt** [comment]
The other day I landed https://github.com/w3c/csswg-drafts/pull/11913 in response to a resolution regarding computed/resolved values of the border-*-width properties. Blink and Gecko are in the process of landing implementation changes for that.

Subsequent to landing that PR, I discovered this discussion. Not sure if the change I landed impacts the path to REC or what next steps might be; I'd be happy to revert the change to backgrounds-3 and move it into borders-4 if that's the right thing to do (in fact, I think it should be in borders-4 either way).

**Comment by SebastianZ** [comment]
@kbabbitt:

> Not sure if the change I landed impacts the path to REC or what next steps might be; I'd be happy to revert the change to backgrounds-3 and move it into borders-4 if that's the right thing to do

I don't have a strong opinion on that. Though @fantasai and @bradkemper are the editors of level 3, so maybe they have an opinion. For now, I've added it to the [to-do list](https://github.com/w3c/csswg-drafts/issues/10010#issuecomment-3333492408).

> (in fact, I think it should be in borders-4 either way).

Correct! I've incorporated the rest of CSS Backgrounds 3 into CSS Backgrounds 4 and CSS Borders 4 lately (see #12972 and #12856). So any change done to CSS Backgrounds 3 should also be done to CSS Backgrounds 4 or CSS Borders 4 (depending on what's affected) from now on to keep them in sync.

Sebastian

**Comment by kbabbitt** [comment]
> Correct! I've incorporated the rest of CSS Backgrounds 3 into CSS Backgrounds 4 and CSS Borders 4 lately (see [#12972](https://github.com/w3c/csswg-drafts/pull/12972) and [#12856](https://github.com/w3c/csswg-drafts/pull/12856)). So any change done to CSS Backgrounds 3 should also be done to CSS Backgrounds 4 or CSS Borders 4 (depending on what's affected) from now on to keep them in sync.

Thanks @SebastianZ, I opened https://github.com/w3c/csswg-drafts/pull/13208 for this change.
