### ISSUE TITLE
[css-values-3][spec-rec] Publish CSS Values & Units 3 as a REC

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#4846]
From @atanassov's [last email](https://lists.w3.org/Archives/Member/w3c-css-wg/2018JanMar/0110.html), given having something public to point at about what blocks publishing it would be nice:

- DOC - https://drafts.csswg.org/css-values-3/issues-cr-2016
- Looks like only one issue?

AIUI the blockers status are:

- [ ] Write as DOC for the 2019 CR
- [ ] #4840 (drop the at-risk multi-arg `attr()`)
- [ ] Check references v. the [normative reference policy](https://www.w3.org/2013/09/normative-references); currently non-REC normative refs:
  - [ ] [CSS-CASCADE-4]
  - [ ] [CSS-COLOR-4]
  - [ ] [CSS-COUNTER-STYLES-3]
  - [ ] [CSS-DISPLAY-3]
  - [ ] [CSS-IMAGES-4]
  - [ ] [CSS-OVERFLOW-3]
  - [ ] [CSS-SIZING-3]
  - [ ] [CSS-UI-4]
  - [ ] [CSS-VALUES-4] (note this is a normative citation from level 3 to level 4!)
  - [ ] [CSS-WRITING-MODES-4]
  - [ ] [CSS3-BACKGROUND]
  - [ ] [CSS3-IMAGES]
  - [ ] [CSS3CASCADE]
  - [ ] [CSS3PAGE]
  - [ ] [CSS3SYN]
  - [ ] [CSSOM]
  - [ ] [MEDIAQ]
  - [ ] [SELECTORS-4] (note we also cite [SELECTORS-3] which is a REC)
 - [ ] Check test suite status and write an implementation report

**Comment by svgeesus** [comment]
>  Check test suite status and write an implementation report

The report is automatically generated. [Here is the current one](https://test.csswg.org/harness/results/css-values-3_dev/grouped/) (39 of 70 required tests meet CR exit criteria).

The main things missing are passes on `ch` units in both horizontal and vertical writing.

There are also missing test results for Blink, Webkit (and also Edge, if anyone has a pre-Blink Edge around for testing)

**Comment by svgeesus** [comment]
Currently [6 open, 41 closed issues](https://github.com/w3c/csswg-drafts/labels/css-values-3) (one of them being this meta-issue).

**Comment by gsnedders** [comment]
> The report is automatically generated. Here is the current one (39 of 70 required tests meet CR exit criteria).

Well, yes, but I've almost never seen an implementation report accepted without any sort of human-written element explaining failures. :)

**Comment by gsnedders** [comment]
> and also Edge, if anyone has a pre-Blink Edge around for testing

https://wpt.fyi/results/css/css-values?label=master&product=edge-44.17763.1.0&product=chrome%5Bstable%5D&product=firefox%5Bstable%5D&product=safari%5Bstable%5D&aligned has results for 4b7986331d2e2ee1e63ed42e392d36946904327c, which is admittedly now a while ago.

**Comment by svgeesus** [comment]
Now [57 of 70 required tests meet CR exit criteria](https://test.csswg.org/harness/results/css-values-3_dev/grouped/) Problems are `ch` unit, especially in vertical writing; `calc` in `transform`; `calc` in `offset-position`, and calc in `text-combine-upright: digits` .

I suspect carefully checking the correctness of those tests, then filing individual bugs on browser engines, would help drive those fails towards zero.

And yes, a human-written addendum that the fails are more to do with the other specs being tested (this is _particularly_ true with a spec like V&U) will be needed.

**Comment by svgeesus** [comment]
I removed the `css-values-3`  tag on https://github.com/w3c/csswg-drafts/issues/4329 and the rest look like low-hanging fruit that could be closed off speedily.

**Comment by svgeesus** [comment]
>  [CSS-VALUES-4] (note this is a normative citation from level 3 to level 4!)

Okay that is a bit whacked.

 [css-values-4] defines the following terms:

    %
    angle
    frequency
    integer
    length
    number
    string
    time
    toggle()
    url 

I'm guessing that is incorrect bikeshed syntax, and should be fixed.

**Comment by tabatkins** [comment]
It can be fixed manually (using link-defaults), but the reason it's happening is that I currently only distinguish between "ED" and "TR" statuses for definitions; I don't go into more fine-grained divisions within TR. As such, Values 4 is considered a perfectly suitable definition source.

**Comment by svgeesus** [comment]
So (four years later):

- 1 open issue (this one)
- test suite on WPT [with 3301 tests](https://wpt.fyi/results/css/css-values?label=experimental&label=master&aligned) of which Firefox has the highest score **3298/3301**, while Chrome has the lowest **2606/3301**.
- few [changes since 22 March 2024 CRD](https://drafts.csswg.org/css-values-3/#changes)

Assessing the level of implementation support is tricky because the values and units can't be implemented by themselves; the actual WPT are examples where other specifications are using them. There is a [manually generated implementation report](https://drafts.csswg.org/css-values-3/implementation-report.html) but that was last updated April 2021.

@tabatkins @fantasai how close do you think this is to getting to REC? It would need another CR Snapshot first, of course.

**Comment by svgeesus** [comment]
> * test suite on WPT [with 3301 tests](https://wpt.fyi/results/css/css-values?label=experimental&label=master&aligned)

Seems pretty static, now 3302 tests.

<img width="1139" height="235" alt="Image" src="https://github.com/user-attachments/assets/2af10fc1-238d-45ba-ae4a-fc3a7c9e91a1" />

and [changes not updated](https://drafts.csswg.org/css-values-3/#changes) but [almost no changes since last CRS](https://github.com/w3c/csswg-drafts/commits/main/css-values-3/Overview.bs)

A[CR draft was published in 2024](https://www.w3.org/TR/2024/CRD-css-values-3-20240322/) so @fantasai @tabatkins how much plea-bargaining would an implementation report have to do to be able to exit CR? It seems tht Firefox is still in the lead, so we need one other implementation to improve.

And should we publish a CR Snapshot to incorporate the [one tiny but non-editorial change](https://github.com/w3c/csswg-drafts/commit/4d997d9b061360580b80385515bca009c3f0dc1f#diff-2e9de5b8f86c45f34eab818168ca5773e588678b632e2f5f8dcf5227c5a83e19)?

**Comment by gsnedders** [comment]
A [quick glance at tests with less than two passes](https://wpt.fyi/results/css/css-values?q=count%3A%3C2%28status%3Apass%7Cstatus%3Aok%29&run_id=4873129982951424&run_id=5174194842370048&run_id=5168153132007424) suggests that it's mostly things in later levels which don't pass.

It would be both easier to understand where things stand if there were subdirectories corresponding to the different sections of the spec, rather than having 285 files in a single directory, and easier to exclude additions from Level 4 and Level 5.

**Comment by SebastianZ** [comment]
Looking at the [main portion of failing tests in the spec](http://drafts.csswg.org/css-values-3/#:~:text=shape-outside-circle), they refer to values in CSS Shapes like https://wpt.fyi/results/css/css-shapes/shape-outside/values/shape-outside-circle-004.html?label=master&label=experimental&aligned.

And skimming through those tests, the results basically seem ok - Blink and WebKit either try to be smart about the computed value or just return the authored value - though those sometimes differ from the expected value, which often uses (unnecessary) `calc()` expressions.

For what it's worth, there's also a [Chromium bug related to those tests](https://issues.chromium.org/issues/40149424).

Sebastian
