### ISSUE TITLE
Wide Review of CSS Color 4

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#4943]
Wide review status for CSS Color 4

Horizontal review
- [x] [TAG review of Lab, LCH](https://github.com/w3ctag/design-reviews/issues/488)
 - [x] [A11y review](https://github.com/w3c/css-a11y/issues/34)
 - [x] [I18n review](https://github.com/w3c/i18n-request/issues/116#issuecomment-629000587) ([self-review](https://github.com/w3c/csswg-drafts/issues/5034)) ([tracked](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+label%3Ai18n-needs-resolution+label%3Acss-color-4))
 - [x] [PING review](https://github.com/w3cping/tracking-issues/issues/121) ([privacy & security section](https://drafts.csswg.org/css-color-4/#priv-sec)) ([tracked](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+label%3Aprivacy-needs-resolution+label%3Acss-color-4+))
- [x] [Security review](https://github.com/w3c/csswg-drafts/issues/5499) ([tracked](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+label%3Asecurity-needs-resolution+label%3Acss-color-4+))

Technical review
 - [x] ColorwebCG: specification presented to ColorWeb CG at TPAC 2020
 - [x] ICC: this specification has been presented to the International Color Consortium a few times. There is [one outstanding issue](https://github.com/w3c/csswg-drafts/issues/3449) regarding a better default CMYK profile.

**Comment by svgeesus** [comment]
[[CSS-COLOR-4] Security/Privacy: Incognito mode](https://github.com/w3c/csswg-drafts/issues/5553)

[[css-color-4] Security: handling of color-profiles](https://github.com/w3c/csswg-drafts/issues/5552)

**Comment by fantasai** [comment]
Um. I think it's not great that we're requesting wide review on a draft that has not been published since a year ago. Can we get an updated publication out so that there isn't such a huge discrepency between the official draft and the current CSSWG consensus?

**Comment by svgeesus** [comment]
Well, I was instead requesting wide review before going to CR.

However, I'm fine with pushing an updated WD meanwhile.

**Comment by atanassov** [comment]
@fantasai, @svgeesus, Since this is only a WD re-publishing I am going to save WG time and call the resolution for you here. 

RESOLVED: Publish a new WD of CSS Color 4

cc: @astearns

**Comment by fantasai** [comment]
@svgeesus We can publish whenever we want, so no need to be precious with the publications! If the draft is in the state ready to present for external review, then it is certainly in a state acceptable for publication on /TR. (Good rule of thumb is, if you're asking for external review--not just to confirm that proposed edits are correct and good and have WG consensus--you should be able to request it against the /TR copy; if not, it means your spec is out-of-date and should be republished.)

**Comment by svgeesus** [comment]
[Published 12 Nov 2020](https://www.w3.org/TR/2020/WD-css-color-4-20201112/)

**Comment by svgeesus** [comment]
The [privacy review has been closed](https://github.com/w3cping/privacy-reviews/issues/13)

**Comment by svgeesus** [comment]
As of date of /TR publication, [15 issues remain open](https://github.com/w3c/csswg-drafts/labels/css-color-4) including this one.

**Comment by svgeesus** [comment]
[Horizontal Review report](https://www.w3.org/PM/horizontal/review.html?shortname=css-color)
