### ISSUE TITLE
[css-fonts-4] I18n self-review checklist

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5030]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [ ] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    This specification is not used to generate text.
    
2. [x] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    Yes, this is the main focus of this specification. See following comments.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

   No

4. [ ] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    In general no. However, see [Localized name matching](https://drafts.csswg.org/css-fonts-4/#localized-name-matching) for matching on localized font names. For example, an implementation must match on `굴림체` (Korean) as well as `GulimChe` (Latin)

5. [ ] _If the spec (or its implementation) sorts text_

    No

6. [ ] _If the spec (or its implementation) captures user input_

    No

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    No

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    Characters are processed as Unicode codepoints. Character encoding is not dealt with in this specification.  The [`unicode-range` descriptor](https://drafts.csswg.org/css-fonts-4/#unicode-range-desc) defines the set of Unicode codepoints that may be supported by the font face for which it is declared. This serves as a download hint (don't download fonts that won't cover the text you are trying to render) and also a way to _disallow_ use of a font for codepoint ranges that you don't want to be used.

9. [ ] _If the spec (or its implementation) defines markup._

    No

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    No

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    No

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    Yes, some font choices are informed by cultural norms such as the association of particular typefaces with expected usage (formal, playful, archaic, governmental, religious)

**Comment by svgeesus** [comment]
**Text decoration**

1. [ ] _Text decoration such as underline and overline should allow lines to skip ink.

2. [ ] _It should be possible to specify the distance of overlines and underlines from the text.

**Comment by svgeesus** [comment]
**Vertical text**

1. [ ] _It should be possible to render text vertically for languages such as Japanese, Chinese, Korean, Mongolian, etc. 

2. [ ] _Vertical text must support line progression from LTR (eg. Mongolian) and RTL (eg. Japanese) 

3. [ ] _By default, text decoration, ruby, and the like in vertical text where lines are stacked from left to right (eg. Mongolian) should appear on the same side as for CJK vertical text. Placement should not rely on the before and after line locations.

4. [ ] _Vertical writing modes that are equivalent to the vertical- values in CSS (only) should use UTR50 to apply default text orientation of characters. (This does not apply to writing modes that are equivalent to sideways- in CSS.)

5. [ ] _By default, glyphs of scripts that are normally horizontal should run along a line in vertical text such that the top of the character is toward the right side of the vertical line, but there should also be a mechanism to allow them to progress down the line in upright orientation. Such a mechanism should use grapheme clusters as a minimum text unit, but where necessary allow syllabic clusters to be treated as a unit when they involve more than one grapheme cluster.

6. [ ] _Upright Arabic text in vertical lines should use isolated letter forms and the order of text should read top to bottom.

7. [ ] _It should be possible for some sequences of characters (particularly digits) to run horizontally within vertical lines (tate chu yoko).

8. [ ] _Writing modes should provide values like sideways-lr and sideways-rl in CSS to allow for vertical rotation of lines of horizontal script text. UTR50 is not applicable for these cases.

**Comment by svgeesus** [comment]
**Ruby text annotations**

1. [ ] _Ruby style annotations alongside base text should be supported for Chinese, Japanese, Korean and Mongolian text, in both horizontal and vertical writing modes._

2. [ ] _Ruby implementations should support zhuyin fuhao (bopomofo) ruby for Traditional Chinese._

3. [ ] _Ruby implementations should support a tabular content model (such that ruby contents can be arranged in a sequence approximating to rb rb rt rt)._

4. [ ] _Ruby implementations should make it possible to use an explicit rb tag for ruby bases._

5. [ ] _​Ruby implementations should allow annotations to appear on either or both sides of the base text._

**Comment by svgeesus** [comment]
**Miscellaneous**

1. [ ] _Line heights must allow for characters that are taller than English._

2. [ ] _Box sizes must allow for text expansion in translation._

3. [ ] _Line wrapping should take into account the special rules needed for non-Latin scripts_

4. [ ] _Avoid specifying presentational tags, such as b for bold, and i for italic._

**Comment by svgeesus** [comment]
**Other notable items**

- [the font-language-override property](https://drafts.csswg.org/css-fonts-4/#font-language-override-prop) (previously in Fonts 3, moved to Fonts 4 for lack of implementations):

> authors may need to specify a language system that differs from the content language, for example due to the need to mimic another language’s typographic traditions

- [The font-variant-emoji property](https://drafts.csswg.org/css-fonts-4/#font-variant-emoji-prop)

> allows web authors to select whether emoji presentation or text presentation is used for certain emoji code points ... Only the code points listed by Unicode as contributing to a Unicode emoji presentation sequence are affected by this property.

- [expanded set of Generic Font families](https://drafts.csswg.org/css-fonts-4/#generic-font-families) including [Fangsong](https://drafts.csswg.org/css-fonts-4/#fangsong-def). Current [open issue on what generics are for](https://github.com/w3c/csswg-drafts/issues/4910).

**Comment by r12a** [comment]
Thanks for this @svgeesus. Nicely done.  I'll ask the i18n WG (including myself) to look at the details in the spec for items that you've highlighted, and we'll raise separate issues for any comments that arise, if any.

**Comment by r12a** [comment]
There are one or two issues already open (eg. for generic font families).  I added just one other small one at https://github.com/w3c/csswg-drafts/issues/5295

Otherwise this all looks good to me. Thanks.

**Comment by svgeesus** [comment]
Thanks for the report, @r12a.

- [ ]  There is the privacy/fingerprinting local font issue, whose mitigation has a significant I18n component [limit local fonts to those selected by users in browser settings](https://github.com/w3c/csswg-drafts/issues/4497)

- [ ]  And the whole slew of generic font issues, whose meta-issue is [Criteria for generic font families](https://github.com/w3c/csswg-drafts/issues/4910) with [a list of related issues](https://github.com/w3c/csswg-drafts/issues/4910#issuecomment-618152366)

- [ ] The [horizontal/vertical kerning](https://github.com/w3c/csswg-drafts/issues/5295) one you just raised

- [ ]  Lastly, the [default caseless matching](https://github.com/w3c/csswg-drafts/issues/4652) issue

**Comment by r12a** [comment]
Fwiw, here is a list of open issues for css-fonts-4 that the i18n WG is currently tracking:
https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+label%3Acss-fonts-4+label%3Ai18n-tracker

**Comment by svgeesus** [comment]
> Otherwise this all looks good to me. Thanks.

Closing, as individual issues have been filed separately.
