### ISSUE TITLE
I18n self-review of CSS Color 4

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5034]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

1. [ ] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

    No
    
2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    No

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

   No

4. [ ] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    No

5. [ ] _If the spec (or its implementation) sorts text_

    No

6. [ ] _If the spec (or its implementation) captures user input_

    No

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    No

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._

   No

9. [ ] _If the spec (or its implementation) defines markup._

    No

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    No

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    No

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    Yes, some color choices have associations  which vary by culture.

**Comment by svgeesus** [comment]
@r12a ok to close this on our end?

https://github.com/w3c/i18n-request/issues/116
https://github.com/w3c/i18n-activity/issues/897

**Comment by svgeesus** [comment]
[Completed](https://github.com/w3c/i18n-request/issues/116#issuecomment-688980031)
