### ISSUE TITLE
[css-conditional-3] I18n Short Review answers

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5568]
Short i18n review checklist is [here](http://w3c.github.io/i18n-activity/reviews/shortchecklist)

These review answers are for [CSS Conditional Rules Module Level 3](https://drafts.csswg.org/css-conditional-3/) which allows stylesheet authors to make certain sections conditional  on support (@supports), with fallback for older browsers. This results in more robust stylesheets.

1. [ ] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_

   No.
    
2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._

    No.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._

    No.

4. [x] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_

    It allows stylesheets to do  matching of implementation-supported CSS properties, values, and descriptors.

5. [ ] _If the spec (or its implementation) sorts text_

    No.

6. [ ] _If the spec (or its implementation) captures user input_

    No.

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_

    No.

8. [x] _If the spec (or its implementation) allows any character encoding other than UTF-8._

    Same answer for all CSS specifications, [@charset](https://drafts.csswg.org/css-syntax-3/#at-ruledef-charset), which is defined in CSS Syntax, is used to declare the character encoding of a CS stylesheet.

9. [ ] _If the spec (or its implementation) defines markup._

    No.

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_

    No.

11. [ ] _If the spec (or its implementation) describes a format or data that is likely to need localization._

    No.

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_

    No.

**Comment by svgeesus** [comment]
I see that @r12a [reviewed and had no comments](https://github.com/w3c/i18n-request/issues/136)

**Comment by xfq** [comment]
Can we close this now?
