### ISSUE TITLE
[css-conditional-3] Wide Review status

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#5569]
- [x] A11y review (nothing in [FAST](https://w3c.github.io/apa/fast/checklist.html) seemed relevant)
 - [x] I18n review ([self-review](https://github.com/w3c/csswg-drafts/issues/5568))
 - [x] Privacy review ([privacy & security section](https://drafts.csswg.org/css-conditional-3/#priv-sec))
 - [x] Security review  ([Security review answers](https://github.com/w3c/csswg-drafts/issues/5567))

[Disposition of comments](https://drafts.csswg.org/css-conditional-3/issues-cr-2013.html)

[Previous CR transition request, from 2013](https://lists.w3.org/Archives/Member/chairs/2013JanMar/0130.html) (Member only, for no good reason)

**Comment by svgeesus** [comment]
[A11y review requested 1 Oct 2020](https://lists.w3.org/Archives/Public/public-apa/2020Oct/0000.html)

**Comment by svgeesus** [comment]
[Security review requested 1 Oct 2020](https://lists.w3.org/Archives/Public/public-web-security/2020Oct/0000.html)

**Comment by svgeesus** [comment]
[Privacy review requested 1 Oct 2020](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0000.html)

**Comment by svgeesus** [comment]
[I18n review requested 1 Oct 2020](https://github.com/w3c/csswg-drafts/issues/5568)

**Comment by sandandsnow** [comment]
re: PING privacy review, our next meeting is 5 November, rather than 29 October

**Comment by svgeesus** [comment]
> re: PING privacy review, our next meeting is 5 Novembe

I see from [minutes of the 5 Nov PING meeting](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20201105) that review was assigned to Jeffrey.

**Comment by svgeesus** [comment]
I see that @r12a [reviewed and had no comments](https://github.com/w3c/i18n-request/issues/136)

**Comment by svgeesus** [comment]
I see that the CSS Conditional 3 privacy review [happened on 19 Nov](https://www.w3.org/Privacy/IG/summaries/PING-minutes-20201119#3-css-conditional-3) but it is not clear from those minutes whether privacy issues are going to be raised, or if privacy review is complete. @jyasskin @sandandsnow could you clarify?

**Comment by jyasskin** [comment]
I believe the meeting agreed with my sense that you've covered the privacy considerations well in the spec, and nothing needs to change. As the privacy consideration section calls out, we're expecting to have a more interesting discussion about the Media Queries spec once that goes to wide review.

**Comment by svgeesus** [comment]
@fantasai horizontal review is complete, changes is up to date, we have a WG resolution for CRD; so okay to open a transitions issue for CRD?

**Comment by svgeesus** [comment]
[CR Snapshot published 8 December 2020](https://www.w3.org/TR/2020/CR-css-conditional-3-20201208/)
Review end date 15 January 2021
Exclusion opportunity until 06 February 2021

**Comment by xfq** [comment]
Can we close this now?
