### ISSUE TITLE
[css-text-3] Horizontal Review

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5587]
- [x] A11y review [requested](https://lists.w3.org/Archives/Public/public-apa/2020Oct/0004.html) and [completed](https://lists.w3.org/Archives/Public/public-apa/2020Oct/0006.html)
 - [x] I18n review [requested](https://github.com/w3c/i18n-request/issues/146) and [completed](https://github.com/w3c/i18n-request/issues/146#issuecomment-742670641)
 - [ ] Privacy review [requested](https://lists.w3.org/Archives/Public/www-style/2020Oct/0002.html), [acknowledged](https://lists.w3.org/Archives/Public/www-style/2020Oct/0007.html)
 - [ ] Security review [requested](https://lists.w3.org/Archives/Public/www-style/2020Oct/0003.html)
 - [x] TAG review [requested](https://github.com/w3ctag/design-reviews/issues/581) and [completed](https://github.com/w3ctag/design-reviews/issues/581#issuecomment-767250475)

**Comment by fantasai** [comment]
Privacy and Security timed out. Transition filed and completed December 2020.

**Comment by svgeesus** [comment]
[css text 3 publication history](https://www.w3.org/standards/history/css-text-3)
