### ISSUE TITLE
Republishing Tasks Permathread

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5613]
Edit this comment to add things to the list.
Include a link to the latest resolution to publish and/or Agenda+ request for permission to publish, so we can follow-up.
Checkmark means has a WG resolution. Remove from list once actually published.
Link the transition request, once it has been made.

See also [Estimated Publication Badness Chart](http://fantasai.inkedblade.net/style/reports/csswg-status-radar/) and [Transition Requests](https://github.com/w3c/transitions/issues)

- [ ] Animation Worklet
- [x] Layout API
- [x] Paint API
- [x] Properties & Values API
- [x] Typed OM
- [x] RESOLVED: Accept the [PR](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2FTR%2Fcss-contain-2%2F&doc2=https%3A%2F%2Fdrafts.csswg.org%2Fcss-contain-2%2F#cv-notes)  and republishing WD of containment 2
- [x] [scoping](https://www.w3.org/blog/CSS/2021/05/26/minutes-telecon-2021-05-26/) [shadow](https://lists.w3.org/Archives/Public/www-style/2021Sep/0001.html)
- [x] [CR of Color Adjust](https://www.w3.org/blog/CSS/2021/09/08/minutes-2021-09-08/)
- [x] [WD of Highlight API](https://lists.w3.org/Archives/Public/www-style/2021Nov/0001.html)

**Comment by svgeesus** [comment]
> Include a link to the latest resolution to publish and/or Agenda+ request for permission to publish, so we can follow-up.
Checkmark means has a WG resolution.

So once there is a resolution (indicated by a checkmark) the link should also be updated to point to the actual resolution. Because a transition request can't link to an Agenda+ email, it needs to link to the actual resolution

**Comment by svgeesus** [comment]
It would also be helpful if resolutions included the stage that it was resolved to publish AT. For example FPWD, WD, etc. And to note that some are republishing requests, while others are transition requests (publication being the last stage in a sucessfull transition).

**Comment by svgeesus** [comment]
> RESOLVED: Publish sizing-4

[Published 20 Oct 2020](https://www.w3.org/TR/2020/WD-css-sizing-4-20201020/)

**Comment by svgeesus** [comment]
> RESOLVED: publish highlight-api (FPWD)

[Published 22 Oct 2020](https://www.w3.org/TR/2020/WD-css-highlight-api-1-20201022/)

**Comment by svgeesus** [comment]
> sizing-3 (once resolved edits are in)

Is that a new publication since [the WD of 23 October](https://www.w3.org/TR/2020/WD-css-sizing-3-20201023/)

There is no link.

**Comment by svgeesus** [comment]
> [RESOLVED](https://lists.w3.org/Archives/Public/www-style/2020Nov/0011.html): Republish a new WD [of Fonts 4]

[Published 17 Nov 2020](https://www.w3.org/TR/2020/WD-css-fonts-4-20201117/)

**Comment by svgeesus** [comment]
> [RESOLVED](https://lists.w3.org/Archives/Public/www-style/2020Nov/0011.html): Publish a new WD for Values 4

[Published 11 Nov 2020](https://www.w3.org/TR/2020/WD-css-values-4-20201111/)

**Comment by svgeesus** [comment]
>  Animation Worklet
Layout API
Paint API
Properties & Values API
Typed OM

These don't have links, and looking back the last 3 months on www-style didn't turn up any minuted resolutions. I may have missed them, or was that even further back?

**Comment by svgeesus** [comment]
CR snapshot of CSS Conditional 3 [published 8 Dec 2020](https://www.w3.org/TR/2020/CR-css-conditional-3-20201208/)

**Comment by svgeesus** [comment]
@fantasai some status questions earlier in the thread, you may have missed

**Comment by svgeesus** [comment]
Added the mega  CR requests from [16 Dec telcon](https://www.w3.org/2020/12/16-css-irc)

@fantasai [my earlier questions?](https://github.com/w3c/csswg-drafts/issues/5613#issuecomment-734369551)

**Comment by fantasai** [comment]
Houdini is so far behind, the [resolutions to publish are from 2019](https://lists.w3.org/Archives/Public/public-houdini/2019Jul/0002.html).

**Comment by svgeesus** [comment]
> update Containment 1 REC

Publication requested 18 Dec, expected 22 Dec.

**Comment by svgeesus** [comment]
> Publish snapshot 2020 as a note

Publication requested 17 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
> Move css box model 3 to CR

Publication requested 21 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
> Cascade 3 (PR)

Publication requested 21 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
> publish a new CR for Backgrounds and Borders 3

Publication requested 21 Dec, expected 22 Dec

**Comment by svgeesus** [comment]
> CSS Text 3

Publication requested 19 Dec, [published 22 Dec](https://www.w3.org/TR/2020/CR-css-text-3-20201222/)

**Comment by svgeesus** [comment]
> FPWD css-cascade-5

[Published 19 Jan 2021](https://www.w3.org/TR/2021/WD-css-cascade-5-20210119/)

**Comment by svgeesus** [comment]
> 26 May **Resolved**: Republish WD of Color 4 & Color 5

Published Color 4 [1 June 2021](https://www.w3.org/TR/2021/WD-css-color-4-20210601/) and Color 5 [1 June 2021](https://www.w3.org/TR/2021/WD-css-color-5-20210601/)

**Comment by svgeesus** [comment]
@fantasai your Estimated Publication Badness Chart was last updated 6 months ago. Is it something you plan to maintain over time, or is it more a one-time snapshot sort of thing?

**Comment by svgeesus** [comment]
CSS Masking 1 [published 5 Aug 2021](https://www.w3.org/TR/2021/CRD-css-masking-1-20210805/)
CSS Color 3 [published  5 Aug 2021](https://www.w3.org/TR/2021/REC-css-color-3-20210805/)

**Comment by svgeesus** [comment]
CSS Fonts 5 [FPWD 29 Jun 2021](https://www.w3.org/TR/2021/WD-css-fonts-5-20210629/)

**Comment by frivoal** [comment]
CSS Scrollbars 1 WD [published 5 August 2021](https://www.w3.org/TR/2021/WD-css-scrollbars-1-20210805/)

**Comment by svgeesus** [comment]
CRD of CSS Variables [published 11 Nov](https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/)

**Comment by tabatkins** [comment]
Closing in favor of #6900 because it has an easier-to-remember number. (h/t @fantasai)
