### ISSUE TITLE
[css-box-3] Horizontal Review 

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5678]
- [ ] A11y review [requested](https://lists.w3.org/Archives/Public/public-apa/2020Oct/0032.html)
 - [x] I18n review [requested](https://github.com/w3c/i18n-request/issues/135) and [completed](https://github.com/w3c/i18n-request/issues/135#issuecomment-728408694)
 - [ ] Privacy review [requested](https://lists.w3.org/Archives/Public/public-privacy/2020OctDec/0025.html)
 - [ ] Security review [requested](https://lists.w3.org/Archives/Public/public-web-security/2020Oct/0010.html)
 - [ ] TAG review (skipping so as not to waste anyone's time; there's [nothing new in this spec compared to CSS2](https://www.w3.org/TR/css-box-3/#changes))

**Comment by svgeesus** [comment]
[CSS 3 Box REC published 6 Apr 2023](https://www.w3.org/TR/2023/REC-css-box-3-20230406/)
