### ISSUE TITLE
[css-color-adjust-1] Horizontal Review

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#5768]
- [x] A11y review [requested](https://lists.w3.org/Archives/Public/public-apa/2020Nov/0004.html) and [completed](https://github.com/w3c/css-a11y/issues/36#issuecomment-759162880)
 - [x] I18n review [requested](https://github.com/w3c/i18n-request/issues/137) and [completed](https://github.com/w3c/i18n-request/issues/137#issuecomment-729622367)
 - [x] Privacy review [requested](https://lists.w3.org/Archives/Public/www-style/2020Dec/0004.html) and [completed](https://github.com/w3cping/privacy-request/issues/41#issuecomment-840873512) 
 - [x] Security review [requested](https://lists.w3.org/Archives/Public/www-style/2020Dec/0005.html) and timed out
 - [x] TAG review [requested](https://github.com/w3ctag/design-reviews/issues/583) and [completed](https://github.com/w3ctag/design-reviews/issues/583#issuecomment-839947946)

**Comment by svgeesus** [comment]
Which of the editors @fantasai @lilles @atanassov @tabatkins is making the CR transition request? Is the [changes section](https://drafts.csswg.org/css-color-adjust-1/#changes) up to date?

**Comment by fantasai** [comment]
@svgeesus It was, but then @emilio added https://github.com/w3c/csswg-drafts/pull/6731 which is a significant change. I don't think we have a WG resolution on file for that change either...

**Comment by fantasai** [comment]
Agenda+ to ask if this should go in the snapshot, to resolve on the change to the definition of `normal` in Emilio's PR, to ask if https://github.com/w3c/csswg-drafts/issues/6773 should block CR, and potentially to re-resolve on CR.

**Comment by svgeesus** [comment]
Um, we already resolved to publish the snapshot (although it didn't get published on Tuesday 14th because of two specberus bugs).

@frivoal If the snapshot is still changing should I hold off until January or should I try to get the current snapshot published on Tues 21?

**Comment by astearns** [comment]
Let’s hold off on any more changes to the snapshot in favor of publishing what we have in the time we have left. Then we can add this to 2022.

**Comment by svgeesus** [comment]
Thanks @astearns. Too late for me to work on this today but I can do it tomorrow if I get childcare.

**Comment by astearns** [comment]
Per https://lists.w3.org/Archives/Member/w3c-css-wg/2021OctDec/0120.html (member-only link) we are RESOLVED to add color-adjust-1 to the rough interop section of the next snapshot publication.

**Comment by svgeesus** [comment]
[Privacy review concluded](https://github.com/w3cping/privacy-request/issues/41#issuecomment-840873512) and the one remaining issue on [shielding issue](https://github.com/w3c/csswg-drafts/issues/5710#issuecomment-840772752) was closed later.

**Comment by svgeesus** [comment]
[A11y review concluded, no issues](https://github.com/w3c/a11y-request/issues/18#issuecomment-983869434)

**Comment by svgeesus** [comment]
> Which of the editors @fantasai @lilles @atanassov @tabatkins is making the CR transition request? Is the [changes section](https://drafts.csswg.org/css-color-adjust-1/#changes) up to date?

I updated changes for the one change since last /TR

I have [requested transition to CR](https://github.com/w3c/transitions/issues/409)
