### ISSUE TITLE
[css-multicol-1] Horizontal Review

### ISSUE THREAD

**Issue by rachelandrew** [w3c/csswg-drafts#6103]
- [x] A11y review [requested](https://github.com/w3c/a11y-request/issues/2), [response](https://github.com/w3c/a11y-request/issues/2#issuecomment-836955691)
- [x] I18n review [requested](https://github.com/w3c/i18n-request/issues/153) [response](https://github.com/w3c/csswg-drafts/issues/6301) 
- [x] Privacy review [requested](https://github.com/w3cping/privacy-request/issues/39) [response](https://github.com/w3cping/privacy-request/issues/39#issuecomment-866413907)
- [ ] Security review [requested](https://github.com/w3c/security-request/issues/2)
- [x] TAG review [requested](https://github.com/w3ctag/design-reviews/issues/634), [response](https://github.com/w3ctag/design-reviews/issues/634#issuecomment-865768066)
