### ISSUE TITLE
[css-cascade-4][css-cascade-5] Horizontal Review 

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6120]
- [x] A11y review [requested](https://github.com/w3c/a11y-request/issues/1) and [completed](https://github.com/w3c/a11y-request/issues/1#issuecomment-805985617)
 - [x] I18n review [requested](https://github.com/w3c/i18n-request/issues/152) and completed
 - [x] Privacy review [requested](https://github.com/w3cping/privacy-request/issues/58) and completed
 - [ ] Security review [requested](https://github.com/w3c/security-request/issues/15) and timed out
 - [x] TAG review [requested](https://github.com/w3ctag/design-reviews/issues/678) and completed

**Comment by fantasai** [comment]
(Privacy/Security/TAG review requests are currently pending closure on some `@import` issues; i18n and a11y are filed.)
