### ISSUE TITLE
Replace percentage types by combined <*-percentage> types

### ISSUE THREAD

**Issue by SebastianZ** [w3c/csswg-drafts#646]
CSS Values and Units 3 [defines several combined percentage data types](https://drafts.csswg.org/css-values-3/#percentages), which clarify how the percentages will be computed in the end. These types should be used within the syntax definitions of the other specifications.

Affected specifications are:
- [ ] [CSS 2.2](https://drafts.csswg.org/css2/) (see issue #504)
- [x] [CSS Backgrounds 3](https://drafts.csswg.org/css-backgrounds-3/) (partly done in #263, see issue #645)
- [x] [CSS Backgrounds 4](https://drafts.csswg.org/css-backgrounds-4/) (done in #263)
- [x] [CSS Color 4](https://drafts.csswg.org/css-color-4/) (**No**, because  percentages are not computed to numbers)
- [x] [CSS Fonts 3](https://drafts.csswg.org/css-fonts-3/) (done in #265)
- [x] [CSS Grid 1](https://drafts.csswg.org/css-grid-1/)
- [x] [CSS Images 3](https://drafts.csswg.org/css-images-3/) (done in #268)
- [x] [CSS Images 4](https://drafts.csswg.org/css-images-4/) (done in #268)
- [ ] [CSS Page Floats 3](https://drafts.csswg.org/css-page-floats-3/) see https://github.com/w3c/csswg-drafts/issues/10079
- [x] [CSS Position 3](https://drafts.csswg.org/css-position-3/) (see issue #645)
- [x] [CSS Scroll Snap 1](https://drafts.csswg.org/css-scroll-snap-1/)
- [x] [CSS Shapes 1](https://drafts.csswg.org/css-shapes/)
- [x] [CSS Transforms 1](https://drafts.csswg.org/css-transforms-1/) (see issue #645)
- [x] [CSS Sizing 3](https://drafts.csswg.org/css-sizing-3/)
- [x] [CSS Sizing 4](https://drafts.csswg.org/css-sizing-4/)
- [ ] [CSS Speech 1](https://drafts.csswg.org/css-speech-1/) see #10080
- [x] [CSS Tables 3](https://drafts.csswg.org/css-tables-3/)
- [ ] [CSS Template 1](https://drafts.csswg.org/css-template-1/) see #10081
- [x] [CSS Text 3](https://drafts.csswg.org/css-text-3/) (see issue #645)
- [x] [CSS UI 4](https://drafts.csswg.org/css-ui-4/) (doesn't have any percentages anymore)

Sebastian

**Comment by smfr** [comment]
css-transforms-1 fixed in 26444582d.

**Comment by svgeesus** [comment]
I don't think this is appropriate for CSS Color 4. Percentage does not resolve to a number; actually the reverse. Numbers (which for historical reasons are constrained to assume 8 bits per color component) resolve to a percentage. Higher bit depths are increasingly common. Again for historical reasons, we have to use percentage here where really, if this were being designed now, we actually want a float in the rnge 0.0 to 1.0. But we can't have that because 0 and 1 would mean 0/255 and 1/255, so we have had percentages to stand in for floats since CSS1.

> 	A &lt;number> is equivalent to a &lt;percentage>, but with a different range: 0 again represents the minimum value for the color channel, but 255 represents the maximum. These values come from the fact that many graphics engines store the color channels internally as a single byte, which can hold integers between 0 and 255.

**Comment by tabatkins** [comment]
That's not why Color doesn't need updating; Color doesn't need updating because there is (now) no `<number-percentage>` type, as we realized we can't generally handle that combo in `calc()`.

The `<*-dimension>` types don't imply anything about what range in the non-percentage type maps to 0%-100%. It would be perfectly fine to have the number range `[0-255]` map to the percent range `[0%-100%]`, if that wasn't disallowed by the type-resolving rules.

**Comment by astearns** [comment]
I think there was just one remaining bit in shapes, fixed in https://github.com/w3c/csswg-drafts/commit/60d3770b798ce4be969d1e31ff3f3192972219a4

**Comment by svgeesus** [comment]
The remaining affected specs all have open issues now, so this mega-issue can be closed I think. @SebastianZ ?
