### ISSUE TITLE
[css-display-3] Horizontal Review

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#6516]
- [ ] A11y review [requested](https://github.com/w3c/a11y-request/issues/13#issue-988051432)
 - [ ] I18n review [requested](https://github.com/w3c/i18n-request/issues/164) and [completed](https://github.com/w3c/i18n-request/issues/164#issuecomment-916266118)
 - [ ] Privacy review [requested](https://github.com/w3cping/privacy-request/issues/55) and [completed](https://github.com/w3cping/privacy-request/issues/55#issuecomment-942774259)
 - [ ] Security review [requested](https://github.com/w3c/security-request/issues/13)
 - [ ] TAG review [requested](https://github.com/w3ctag/design-reviews/issues/673) and [completed](https://github.com/w3ctag/design-reviews/issues/673#issuecomment-918643832)

**Comment by fantasai** [comment]
Agenda+ to request CRD publication.
Changes list: https://drafts.csswg.org/css-display-3/#changes
DoC: https://drafts.csswg.org/css-display-3/issues-wd-2020

**Comment by fantasai** [comment]
CRD Published: https://www.w3.org/TR/css-display-3/

**Comment by fantasai** [comment]
Agenda+ to request CR publication. The only changes since the review request was https://github.com/w3c/csswg-drafts/pull/8095 which shouldn't impact Horizontal Review. But the last CRS was May 2020, and we've made some significant changes (pulling in the definitions of `order` and `visibility`, for example) since then.
