### ISSUE TITLE
[css-scrollbars-1] Horizontal Review

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6550]
- [x] A11y review [self review](https://github.com/w3c/csswg-drafts/issues/6555), [review requested](https://github.com/w3c/a11y-request/issues/12), [green light received](https://lists.w3.org/Archives/Public/public-apa/2021Nov/0015.html)
 - [x] I18n review  [self-review](https://github.com/w3c/csswg-drafts/issues/6554), [review requested](https://github.com/w3c/i18n-request/issues/163), [green light received](https://github.com/w3c/i18n-request/issues/163#issuecomment-912593444)
 - [x] Privacy review [self review](https://www.w3.org/TR/css-scrollbars-1/#security-privacy-self-review), [review requested](https://github.com/w3cping/privacy-request/issues/53), [green light received](https://github.com/w3cping/privacy-request/issues/53#issuecomment-912598872)
 - [ ] Security review [self review](https://www.w3.org/TR/css-scrollbars-1/#security-privacy-self-review),  [review requested](https://github.com/w3c/security-request/issues/12)
 - [x] [TAG review completed](https://github.com/w3ctag/design-reviews/issues/563), [green light recieved](https://github.com/w3ctag/design-reviews/issues/563#issuecomment-828532128)

**Comment by frivoal** [comment]
Considering the security review has having timed out, since we did not hear back after 3 months.

Everything else came back clear (with some discussion on a11y which we were able to resolve).

Closing.

**Comment by frivoal** [comment]
(minutes of the WG validating this: https://logs.csswg.org/irc.w3.org/css/2021-12-01/#e1449779)
