### ISSUE TITLE
[css-scrollbars-1] a11y self review

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6555]
Answers based on https://w3c.github.io/apa/fast/checklist.html

* If technology allows visual rendering of content

    It does not. It influences the visual rendering of existing mechanisms, but does not enable visual rendering of additional content. Sub-questions largely do not apply, except:
    * [x] Luminosity and hue contrast can adapt to user requirements.

        `scrollbar-color` lets the author adjust the colors of the scrollbar. Colors are specified as a pair, so that a good contrast between the foreground and background can be provided. In addition, the precise way these colors are applied to the scrollbar is up to the User Agent, which makes it possible for it to take contrast into account. There is also an explicit provision that any explicit user preference with regards to contrast prevails over this property. Other pre-existing mechanisms in CSS allowing the author and user to arrange for different colors schemes and contrast are applicable here (see subsequent questions)

* If technology provides author control over color
    * [x] There is a mechanism for users to override colors of text and user interface components.

        Yes. The UI through which user agents offer to users the ability to chose overriding colors is up to the user agent, but the interaction between user specified colors and author specified colors is specified, and it states that the user preferences win.
    * [x] There is a feature for authors to define semantically available "color classes" that users can easily map to custom colors, and give preference to this vs. coloring objects individually.

        In the broader context of css, this is true (see https://drafts.csswg.org/css-color-adjust-1/). This particular specification offers a narrow control, which still works within that broader framework.

    * [x] There is a feature for users to choose color schemata that work for them. 

        This is true of CSS in general, through various mechanisms like https://drafts.csswg.org/mediaqueries-5/#prefers-contrast, https://drafts.csswg.org/mediaqueries-5/#forced-colors, or https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme, and these are applicable to the property introduced by this specification.

    * [ ] The foreground and background color of an object can be reported to the user via AT. 

        No specific provision is offered to expose the colors of the scrollbar via AT. This could be covered in https://w3c.github.io/css-aam/ if needed.
    * [x] There are ways to set foreground and background colors separately for all objects.

        yes.
    * [ ] Compositing rules for foreground and background colors are well defined. 

        The CSS-WG is aware of this requirement and of the reason for it. However, in this particular case, it is impractical to apply directly, because scrollbars are a native UI component not defined by CSS, and their structure varies between user agents and operating systems. Precise composing rules would require uniformity of scrollbars across operating systems, which is not realistic. With that said, the need to ensure good contrast between foreground and background remains, and it is achieved in this case by giving latitude to the user agent in how it applies the author-supplied foreground and background colors.

* If technology provides features to accept user input…

    This does not change what user input can be taken or how it is taken. Sub-questions do not apply.

* If technology provides user interaction features

    This specification builds upon the pre-existing presence of scrollbars, it does not introduce them. Sub-questions do not apply.

* If technology defines document semantics

    It does not. Sub-questions do not apply.

* If technology provides time-based visual media

    It does not. Sub-questions do not apply.

* If technology provides audio

    It does not. Sub-questions do not apply.
* If technology allows time limits

    It does not. Sub-questions do not apply.
* If technology allows text content

    It does not. Sub-questions do not apply.
* If technology creates objects that don't have an inherent text representation

    It does not. Sub-questions do not apply.
* If technology provides content fallback mechanisms, whether text or other formats

    It does not. Sub-questions do not apply.
* If technology provides visual graphics

    It does not. Sub-questions do not apply.
* If technology provides internationalization support

    It does not. Sub-questions do not apply.
* If technology defines accessible alternative features

    It does not. Sub-questions do not apply.
* If technology provides content directly for end-users

    It does not. Sub-questions do not apply.
* If technology defines an API

    It does not. Sub-questions do not apply.
* If technology defines a transmission protocol

    It does not. Sub-questions do not apply.
