### ISSUE TITLE
[css-variables-1] Horizontal Review

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6808]
- [x] A11y review [self review](https://github.com/w3c/csswg-drafts/issues/6808#issuecomment-965394913) | [Review requested 2021-11-10](https://github.com/w3c/a11y-request/issues/18) 
 - [x] I18n review  [self-review](https://github.com/w3c/csswg-drafts/issues/6808#issuecomment-1033125779) | [Review requested 2022-02-08](https://github.com/w3c/i18n-request/issues/172)
 - [x] Privacy review [self review](https://github.com/w3c/csswg-drafts/issues/6808#issuecomment-1033173803) | [Review requested 2022-02-08](https://github.com/w3cping/privacy-request/issues/79)
 - [x] Security review | [Review requested 2022-02-08](https://github.com/w3c/security-request/issues/21)
 - [x] TAG review | [Review requested 2022-04-22](https://github.com/w3ctag/design-reviews/issues/731)

**Comment by svgeesus** [comment]
None of the [items in the FAST checklist](https://w3c.github.io/apa/fast/checklist.html) seem applicable to this specification.

**Comment by svgeesus** [comment]
[Privacy review concluded](https://github.com/w3cping/privacy-request/issues/41#issuecomment-840873512) and the one remaining issue on [shielding issue](https://github.com/w3c/csswg-drafts/issues/5710#issuecomment-840772752) was closed later.

**Comment by svgeesus** [comment]
[A11y review concluded, no issues](https://github.com/w3c/a11y-request/issues/18#issuecomment-983869434)

**Comment by svgeesus** [comment]
None of the items in the [short I18n review checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) apply to this specification.

**Comment by svgeesus** [comment]
[Questions to Consider](https://w3ctag.github.io/security-questionnaire/#questions)

    _2.1 What information does this feature expose, and for what purposes?_
Whatever the stylesheet author wants to make available. So that it can be reused by name, instead of by hard-to-maintain copy and paste.
    _2.2 Do features in your specification expose the minimum amount of information necessary to implement the intended functionality?_
Yes, the minimum is zero.
    _2.3 Do the features in your specification expose personal information, personally-identifiable information (PII), or information derived from either?_
No
    _2.4 How do the features in your specification deal with sensitive information?_
They don't
    _2.5 Do the features in your specification introduce state that persists across browsing sessions?_
No
    _2.6 Do the features in your specification expose information about the underlying platform to origins?_
No
    _2.7 Does this specification allow an origin to send data to the underlying platform?_
No
    _2.8 Do features in this specification enable access to device sensors?_
No
    _2.9 Do features in this specification enable new script execution/loading mechanisms?_
No
    _2.10 Do features in this specification allow an origin to access other devices?_
No
    _2.11 Do features in this specification allow an origin some measure of control over a user agent’s native UI?_
No
    _2.12 What temporary identifiers do the features in this specification create or expose to the web?_
None
    _2.13 How does this specification distinguish between behavior in first-party and third-party contexts?_
No difference
    _2.14 How do the features in this specification work in the context of a browser’s Private Browsing or Incognito mode?_
No difference
    _2.15 Does this specification have both "Security Considerations" and "Privacy Considerations" sections?_
Yes
    _2.16 Do features in your specification enable origins to downgrade default security protections?_
No
    _2.17 How does your feature handle non-"fully active" documents?_
Not applicable
    _2.18 What should this questionnaire have asked?_
Nothing springs to mind

**Comment by svgeesus** [comment]
A11y review [closed with no issues](https://github.com/w3c/a11y-request/issues/18#issuecomment-983869434)

**Comment by aphillips** [comment]
I18N issues were submitted on 2022-03-10.

**Comment by svgeesus** [comment]
Thanks, @aphillips I [see five open issues](https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+label%3Ai18n-needs-resolution+label%3Acss-variables-1+)

**Comment by svgeesus** [comment]
Privacy review [completed with no issues raised](https://github.com/w3cping/privacy-request/issues/79#issuecomment-1054532046)

**Comment by svgeesus** [comment]
[TAG review completed, no issues](https://github.com/w3ctag/design-reviews/issues/731#issuecomment-1108770884)

**Comment by svgeesus** [comment]
The security review will time-out on 8 May after three months of zero response.

Previous CRD was [11 Nov 2021](https://www.w3.org/TR/2021/CRD-css-variables-1-20211111/)

Horizontal review is complete. Agenda+ to request transition to CR Snapshot.

**Comment by svgeesus** [comment]
Security review timed out with no response
