### ISSUE TITLE
[css-conditional] republish 3,4,5

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6889]
- [x] CSS Conditional 3 -> CRS republication
- [x] CSS Conditional 4 -> CR transition prep
- [x] CSS Conditional 5 -> FPWD with font-tech(), @when, @else

**Comment by fantasai** [comment]
See https://lists.w3.org/Archives/Member/w3c-css-wg/2021OctDec/0116.html for details

**Comment by svgeesus** [comment]
Looks like this didn't pick up the discussion n the call just now

**Comment by fantasai** [comment]
Minutes: https://www.w3.org/2021/12/15-css-minutes.html#t10

**Comment by svgeesus** [comment]
[FPWD CSS Conditional 5](https://www.w3.org/TR/2021/WD-css-conditional-5-20211221/) 21 Dec 2021

**Comment by svgeesus** [comment]
[CSS Conditional 3 CR Snapshot 13 Jan 2022 ](https://www.w3.org/TR/2022/CR-css-conditional-3-20220113/)

**Comment by svgeesus** [comment]
Transition request for [CSS Conditional 4](https://github.com/w3c/transitions/issues/406) is [awaiting WG for Privacy review](https://github.com/w3c/transitions/issues/406#issuecomment-1007736082).

**Comment by svgeesus** [comment]
CSS Conditional 4 [wide review status](https://github.com/w3c/csswg-drafts/issues/6954)
