### ISSUE TITLE
[css-conditional-4] Wide Review status

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#6954]
- [ ] A11y review (nothing in [FAST](https://w3c.github.io/apa/fast/checklist.html) seemed relevant)
 - [x] I18n review (nothing in checklist applies)
 - [x] Privacy review ([privacy section](https://www.w3.org/TR/css-conditional-4/#privacy))
 - [x] Security review 
 - [x]  TAG review
 
[Previous wide review, CSS Conditional 3](https://github.com/w3c/csswg-drafts/issues/5569)

**Comment by svgeesus** [comment]
[Privacy review requested 14 Jan 2022](https://github.com/w3cping/privacy-request/issues/70)

**Comment by svgeesus** [comment]
[I18n review requested 14 Jan 2022](https://github.com/w3c/i18n-request/issues/168)

**Comment by svgeesus** [comment]
[A11y review requested 14 Jan 2022](https://github.com/w3c/a11y-request/issues/20)

**Comment by svgeesus** [comment]
[Security review requested 15 Jan 2022](https://github.com/w3c/security-request/issues/20)

**Comment by svgeesus** [comment]
[TAG review requested 15 Jan 2022](https://github.com/w3ctag/design-reviews/issues/709)

**Comment by svgeesus** [comment]
I18n review [closed with no issues](https://github.com/w3c/i18n-request/issues/168#issuecomment-1025772227)

**Comment by svgeesus** [comment]
Privacy review complete, [no issues found](https://github.com/w3cping/privacy-request/issues/70#issuecomment-1017797960)

**Comment by svgeesus** [comment]
TAG review complete, [no issues found](https://github.com/w3ctag/design-reviews/issues/709#issuecomment-1032076342)

**Comment by svgeesus** [comment]
[Transition request to CR](https://github.com/w3c/transitions/issues/406)

**Comment by svgeesus** [comment]
Security review timed out after one year.
A11y review timed out after one year.
