### ISSUE TITLE
[scroll-animations-1] Early Horizontal Review

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#8102]
- [ ] A11y review [requested for FPWD](https://github.com/w3c/a11y-request/issues/43)
 - [ ] I18n review [requested for FPWD](https://github.com/w3c/i18n-request/issues/197)
 - [ ] Privacy review [seems inapplicable; skipping until later in the process]
 - [ ] Security review [seems inapplicable; skipping until later in the process]
 - [ ] TAG review [requested and completed for ED](https://github.com/w3ctag/design-reviews/issues/521); needs another round

**Comment by flackr** [comment]
@fantasai Are we ready to start the next round of the TAG review?

**Comment by flackr** [comment]
Another TAG review round is started:
https://github.com/w3ctag/design-reviews/issues/828
