### ISSUE TITLE
[css-view-transitions-1] Early Horizontal Review

### ISSUE THREAD

**Issue by khushalsagar** [w3c/csswg-drafts#8109]
- [X] A11y review [requested](https://github.com/w3c/a11y-request/issues/44) and [completed](https://github.com/w3c/a11y-request/issues/44#issuecomment-1431547670)
 - [X] I18n review [requested](https://github.com/w3c/i18n-request/issues/196) and [completed](https://github.com/w3c/i18n-request/issues/196#issuecomment-1656811002)
 - [X] Privacy review [requested](https://github.com/w3cping/privacy-request/issues/107) and [completed](https://github.com/w3cping/privacy-request/issues/107#issuecomment-1440422663)
 - [ ] Security review [requested](https://github.com/w3c/security-request/issues/43)
 - [X] TAG review [requested](https://github.com/w3ctag/design-reviews/issues/748) and [completed](https://github.com/w3ctag/design-reviews/issues/748#issuecomment-1437384846)

**Comment by khushalsagar** [comment]
All reviews are done except security where there hasn't been any response. Closing this now.
